# Generated by Django 4.2.4 on 2023-09-08 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author_photo',
            field=models.FileField(blank=True, max_length=500, upload_to='core/service/reviews/', verbose_name='Фото автора'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='service.review'),
        ),
        migrations.AlterField(
            model_name='reviewphoto',
            name='photo',
            field=models.FileField(max_length=500, upload_to='core/service/reviews/', verbose_name='Фото'),
        ),
    ]
