# Generated by Django 4.2.4 on 2023-09-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_review_author_photo_alter_reviewphoto_field_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'вопрос', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['order'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='reviewphoto',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
