# Generated by Django 4.2.4 on 2023-09-09 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_sofaimage_options'),
        ('service', '0004_alter_reviewphoto_options_review_sofa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('number', models.CharField(max_length=40, verbose_name='Номер телефона')),
                ('message', models.TextField(blank=True, verbose_name='Какая мебель нужна?')),
                ('project_version', models.CharField(blank=True, max_length=10, verbose_name='Версия приложения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user_agent', models.CharField(blank=True, max_length=2000, verbose_name='UserAgent')),
                ('screen_resolution', models.CharField(blank=True, max_length=100, verbose_name='Разрешение экрана')),
                ('browser_language', models.CharField(blank=True, max_length=100, verbose_name='Язык браузера')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='Временная зона')),
                ('cookie', models.TextField(blank=True, max_length=5000, verbose_name='Cookie')),
            ],
            options={
                'verbose_name': 'заявка с сайта',
                'verbose_name_plural': 'Заявки с сайта',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
        migrations.CreateModel(
            name='PopularModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('sofa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.sofa', verbose_name='Диван')),
            ],
            options={
                'verbose_name': 'популярная модель',
                'verbose_name_plural': 'Популярные модели',
                'ordering': ['order'],
            },
        ),
    ]
