# Generated by Django 4.2.4 on 2023-09-10 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_sofa_short_description_alter_sofa_description'),
        ('service', '0005_order_alter_review_order_popularmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sofa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='catalog.sofa', verbose_name='Диван'),
        ),
    ]
