# Generated by Django 4.2.4 on 2023-10-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0006_alter_review_sofa"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="published",
            field=models.BooleanField(default=True, verbose_name="Опубликовано"),
        ),
    ]
