# Generated by Django 4.2.4 on 2023-09-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image_first', models.FileField(max_length=500, upload_to='main/about/', verbose_name='Фото №1')),
                ('image_second', models.FileField(max_length=500, upload_to='main/about/', verbose_name='Фото №2')),
                ('image_third', models.FileField(max_length=500, upload_to='main/about/', verbose_name='Фото №3')),
            ],
            options={
                'verbose_name': '3 - Краткий тизер компании',
                'verbose_name_plural': '3 - Краткий тизер компании',
            },
        ),
        migrations.CreateModel(
            name='ContactsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
                ('whatsapp_link', models.CharField(max_length=255, verbose_name='ссылка на Whatsapp')),
                ('tg_link', models.CharField(max_length=255, verbose_name='ссылка на Telegram')),
                ('image_first', models.FileField(max_length=500, upload_to='main/contacts/', verbose_name='Фото №1')),
                ('image_second', models.FileField(max_length=500, upload_to='main/contacts/', verbose_name='Фото №2')),
            ],
            options={
                'verbose_name': '8 - Контакты',
                'verbose_name_plural': '8 - Контакты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_first', models.CharField(max_length=500, verbose_name='Описание №1')),
                ('description_second', models.CharField(max_length=500, verbose_name='Описание №2')),
            ],
            options={
                'verbose_name': '7 - Доставка',
                'verbose_name_plural': '7 - Доставка',
            },
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(max_length=500, upload_to='main/header/', verbose_name='Лого')),
                ('number', models.CharField(max_length=255, verbose_name='Номер компании')),
            ],
            options={
                'verbose_name': '1 - Навигационная панель',
                'verbose_name_plural': '1 - Навигационная панель',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='main/main/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '2 - Главный блок',
                'verbose_name_plural': '2 - Главный блок',
            },
        ),
        migrations.CreateModel(
            name='RequestBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='main/request/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '5 - Блок заявки',
                'verbose_name_plural': '5 - Блок заявки',
            },
        ),
        migrations.CreateModel(
            name='StagesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_first', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_first', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_second', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_second', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_third', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_third', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_fourth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_fourth', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_fifth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_fifth', models.CharField(max_length=500, verbose_name='Описание')),
                ('image_first', models.FileField(max_length=500, upload_to='main/stages/', verbose_name='Фото №1')),
                ('image_second', models.FileField(max_length=500, upload_to='main/stages/', verbose_name='Фото №2')),
            ],
            options={
                'verbose_name': '6 - Этапы создания мебели',
                'verbose_name_plural': '6 - Этапы создания мебели',
            },
        ),
        migrations.CreateModel(
            name='WhyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_first', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_first', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_second', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_second', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_third', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_third', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_fourth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_fourth', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_fifth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_fifth', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_sixth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_sixth', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '4 - Почему мы?',
                'verbose_name_plural': '4 - Почему мы?',
            },
        ),
    ]
