# Generated by Django 4.2.4 on 2023-08-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddQuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=5000, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '13 - Блок "Остались вопросы?"',
                'verbose_name_plural': '13 - Блок "Остались вопросы?"',
            },
        ),
        migrations.CreateModel(
            name='AdvantageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='advantage/', verbose_name='Фото мебели в интерьере')),
            ],
            options={
                'verbose_name': '5 - Преимущество',
                'verbose_name_plural': '5 - Преимущество',
            },
        ),
        migrations.CreateModel(
            name='CatalogTeaserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, upload_to='catalog_teaser/', verbose_name='Изображение тизера каталога')),
                ('description', models.CharField(max_length=500, verbose_name='Подпись тизера')),
            ],
            options={
                'verbose_name': '3 - Тизер каталога',
                'verbose_name_plural': '3 - Тизер каталога',
            },
        ),
        migrations.CreateModel(
            name='ContactsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('mail', models.CharField(max_length=255, verbose_name='Почта')),
                ('whatsapp_link', models.CharField(max_length=255, verbose_name='ссылка на Whatsapp')),
                ('tg_link', models.CharField(max_length=255, verbose_name='ссылка на Telegram')),
            ],
            options={
                'verbose_name': '14 - Контакты',
                'verbose_name_plural': '14 - Контакты',
            },
        ),
        migrations.CreateModel(
            name='DeliveryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '9 - Доставка',
                'verbose_name_plural': '9 - Доставка',
            },
        ),
        migrations.CreateModel(
            name='HeaderBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(max_length=500, upload_to='header/', verbose_name='Лого')),
                ('number', models.CharField(max_length=255, verbose_name='Номер компании')),
            ],
            options={
                'verbose_name': '1 - Навигационная панель',
                'verbose_name_plural': '1 - Навигационная панель',
            },
        ),
        migrations.CreateModel(
            name='MainBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '2 - Главный блок',
                'verbose_name_plural': '2 - Главный блок',
            },
        ),
        migrations.CreateModel(
            name='PopularModelsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '4  - Популярные модели',
                'verbose_name_plural': '4  - Популярные модели',
            },
        ),
        migrations.CreateModel(
            name='QuestionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('answer', models.CharField(max_length=5000, verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '12 - Частые вопросы',
                'verbose_name_plural': '12 - Частые вопросы',
            },
        ),
        migrations.CreateModel(
            name='RequestBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='request/', verbose_name='Фото мебели в интерьере')),
            ],
            options={
                'verbose_name': '7  - Блок заявки',
                'verbose_name_plural': '7  - Блок заявки',
            },
        ),
        migrations.CreateModel(
            name='ReviewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Имя автора')),
                ('review', models.CharField(max_length=5000, verbose_name='Отзыв')),
                ('image', models.FileField(blank=True, max_length=500, upload_to='reviews/', verbose_name='Фото автора')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '11 - Отзывы',
                'verbose_name_plural': '11 - Отзывы',
            },
        ),
        migrations.CreateModel(
            name='SolutionsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(max_length=500, upload_to='solutions/', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': '10 - Решения наших клиентов',
                'verbose_name_plural': '10 - Решения наших клиентов',
            },
        ),
        migrations.CreateModel(
            name='StagesBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_first', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_first', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_second', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_second', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_third', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_third', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_fourth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_fourth', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_fifth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_fifth', models.CharField(max_length=500, verbose_name='Описание')),
                ('image', models.FileField(max_length=500, upload_to='stages/', verbose_name='Фото мебели в интерьере')),
            ],
            options={
                'verbose_name': '8 - Этапы создания мебели',
                'verbose_name_plural': '8 - Этапы создания мебели',
            },
        ),
        migrations.CreateModel(
            name='WhyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_first', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_first', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_second', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_second', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_third', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_third', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_fourth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_fourth', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_fifth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_fifth', models.CharField(max_length=500, verbose_name='Описание')),
                ('title_sixth', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_sixth', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': '6 - Почему мы?',
                'verbose_name_plural': '6 - Почему мы?',
            },
        ),
    ]
