# Generated by Django 4.2.4 on 2023-09-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_page", "0002_alter_aboutblock_image_first_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="headerblock",
            name="logo_light",
            field=models.FileField(
                default="",
                max_length=500,
                upload_to="main_page/header/",
                verbose_name="Логотип - светлый",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="headerblock",
            name="logo",
            field=models.FileField(
                max_length=500,
                upload_to="main_page/header/",
                verbose_name="Логотип - темный",
            ),
        ),
    ]
