# Generated by Django 4.2.4 on 2023-09-08 04:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('working_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Рабочее название')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('sofa_type', models.CharField(choices=[('straight', 'Прямой'), ('corner', 'Угловой'), ('folding', 'Раскладной'), ('non_folding', 'Нераскладной')], max_length=50, verbose_name='Тип')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('height', models.FloatField(verbose_name='Высота')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('depth', models.FloatField(verbose_name='Глубина')),
                ('seat_depth', models.FloatField(verbose_name='Глубина посадочного места')),
                ('back_height', models.FloatField(verbose_name='Высота спинки')),
                ('armrest_height', models.FloatField(verbose_name='Высота подлокотников')),
                ('other_variants', models.ManyToManyField(blank=True, to='catalog.sofa', verbose_name='Другие варианты исполнения')),
            ],
            options={
                'verbose_name': 'диван',
                'verbose_name_plural': 'Диваны',
            },
        ),
    ]
