# Generated by Django 4.2.4 on 2023-09-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_sofa_options_sofa_order_sofaimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofaimage',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
