# Generated by Django 4.2.4 on 2023-09-10 01:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_sofaimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofa',
            name='short_description',
            field=ckeditor.fields.RichTextField(default='', help_text='Отображается в карточке дивана в каталоге', verbose_name='Короткое описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sofa',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Отображается на странице дивана', verbose_name='Описание'),
        ),
    ]
