# Generated by Django 4.2.4 on 2023-09-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_sofa_short_description_alter_sofa_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sofa",
            name="folding_mechanism",
            field=models.CharField(
                blank=True,
                choices=[("tik-tac", "Тик-так"), ("dolphin", "Дельфин")],
                max_length=50,
                verbose_name="Механизм раскладывания",
            ),
        ),
        migrations.AddField(
            model_name="sofa",
            name="legs_height",
            field=models.FloatField(
                blank=True, default=0, verbose_name="Высота ножек"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sofa",
            name="seat_height",
            field=models.FloatField(
                blank=True, default=0, verbose_name="Высота посадочного места"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sofa",
            name="sofa_form",
            field=models.CharField(
                blank=True,
                choices=[
                    ("straight", "Прямой"),
                    ("corner", "Угловой"),
                    ("p-shaped", " П-образный"),
                ],
                max_length=50,
                verbose_name="Форма",
            ),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="armrest_height",
            field=models.FloatField(blank=True, verbose_name="Высота подлокотников"),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="back_height",
            field=models.FloatField(blank=True, verbose_name="Высота спинки"),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="color",
            field=models.CharField(blank=True, max_length=50, verbose_name="Цвет"),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="seat_depth",
            field=models.FloatField(
                blank=True, verbose_name="Глубина посадочного места"
            ),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="sofa_type",
            field=models.CharField(
                blank=True,
                choices=[("folding", "Раскладной"), ("non_folding", "Нераскладной")],
                max_length=50,
                verbose_name="Тип",
            ),
        ),
    ]
