# Generated by Django 4.2.4 on 2023-09-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_sofa_folding_mechanism_sofa_legs_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sofa",
            name="armrest_height",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Высота подлокотников"
            ),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="back_height",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Высота спинки"
            ),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="legs_height",
            field=models.FloatField(blank=True, null=True, verbose_name="Высота ножек"),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="seat_depth",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Глубина посадочного места"
            ),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="seat_height",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Высота посадочного места"
            ),
        ),
    ]
