# Generated by Django 4.2.4 on 2023-10-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_sofa_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="sofa",
            name="corner_module_depth",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Глубина углового модуля"
            ),
        ),
        migrations.AddField(
            model_name="sofa",
            name="folding_size",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Размер расклада дивана"
            ),
        ),
        migrations.AddField(
            model_name="sofa",
            name="module_depth",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Глубина модуля"
            ),
        ),
        migrations.AddField(
            model_name="sofa",
            name="pouf_depth",
            field=models.FloatField(blank=True, null=True, verbose_name="Глубина пуфа"),
        ),
        migrations.AddField(
            model_name="sofa",
            name="straight_module_depth",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Глубина прямого модуля"
            ),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="depth",
            field=models.FloatField(verbose_name="Общая глубина"),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="height",
            field=models.FloatField(verbose_name="Общая высота"),
        ),
        migrations.AlterField(
            model_name="sofa",
            name="width",
            field=models.FloatField(verbose_name="Общая ширина"),
        ),
    ]
