# Generated by Django 4.2.4 on 2023-10-09 01:54

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_sofa_corner_module_depth_sofa_folding_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sofaimage",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format=None,
                keep_meta=True,
                quality=85,
                scale=None,
                size=[1184, 620],
                upload_to="core/catalog/sofas/",
                verbose_name="Изображение",
            ),
        ),
    ]
