# Generated by Django 4.2.4 on 2023-09-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description_first', models.CharField(max_length=500, verbose_name='Описание №1')),
                ('description_second', models.CharField(max_length=500, verbose_name='Описание №2')),
            ],
            options={
                'verbose_name': '1 - Доставка',
                'verbose_name_plural': '1 - Доставка',
            },
        ),
        migrations.CreateModel(
            name='PaymentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_main', models.CharField(max_length=500, verbose_name='Главный заголовок')),
                ('title_first', models.CharField(max_length=500, verbose_name='Подзаголовок №1')),
                ('description_first', models.CharField(max_length=500, verbose_name='Описание №1')),
                ('payment_first', models.CharField(max_length=3, verbose_name='Процент оплаты №1')),
                ('title_second', models.CharField(max_length=500, verbose_name='Подзаголовок №2')),
                ('description_second', models.CharField(max_length=500, verbose_name='Описание №2')),
                ('payment_second', models.CharField(max_length=3, verbose_name='Процент оплаты №2')),
                ('image_second', models.FileField(max_length=500, upload_to='delivery_page/payment/', verbose_name='Фото №2')),
            ],
            options={
                'verbose_name': '2 - Порядок оплаты',
                'verbose_name_plural': '2- Порядок оплаты',
            },
        ),
    ]
