# Generated by Django 4.2.4 on 2023-09-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentblock',
            name='image_second',
        ),
        migrations.AddField(
            model_name='paymentblock',
            name='image',
            field=models.FileField(default='', max_length=500, upload_to='delivery_page/payment/', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
